name: sphinx-pythia-theme
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
    - ablog
    - jupyter-book
    - sphinx-click
    - sphinx-design
    - sphinx-inline-tabs
    - sphinxext-opengraph
