#######################################################################################
# Book settings
title: ""
logo: images/dummy_logo_dark.svg
author: the Project Pythia Community
copyright: "2024"
email: kpaul@ucar.edu
description: >- # this means to ignore newlines
  This is an example book built with Jupyter Books.

execute:
  execute_notebooks: cache

html:
  favicon: images/favicon.ico
  home_page_in_navbar: false
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  use_download_button: true
  baseurl: https://projectpythia.org/

repository:
  url: https://github.com/ProjectPythia/sphinx-pythia-theme
  branch: main
  path_to_book: docs

launch_buttons:
  notebook_interface: "classic" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  thebe: true

parse:
  myst_substitutions:
    sub3: My _global_ value!
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

bibtex_bibfiles:
  - reference/references.bib

sphinx:
  config:
    html_theme: sphinx_pythia_theme
    html_theme_options:
      github_url: https://github.com/ProjectPythia/sphinx-pythia-theme
      twitter_url: https://twitter.com/project_pythia
      repository_url: https://github.com/ProjectPythia/sphinx-pythia-theme
      extra_navbar: Theme by <a href="https://projectpythia.org">Project Pythia</a>
      navbar_links:
        - name: Documentation
          url: 'index#documentation'
        - name: GitHub
          url: https://github.com/ProjectPythia/sphinx-pythia-theme
          external: True
      page_layouts:
        index: page-banner.html
        standalone: page-standalone.html
      footer_logos:
        NCAR: images/NCAR-contemp-logo-blue.svg
        Unidata: images/Unidata_logo_horizontal_1200x300.svg
        UAlbany: images/UAlbany-A2-logo-purple-gold.svg
      footer_menu:
        - title: "More about..."
          items:
            - name: Project Pythia
              url: https://projectpythia.org/about
            - name: Pangeo
              url: https://pangeo.io
            - name: Project Jupyter
              url: https://jupyter.org
        - title: "Let us know..."
          items:
            - name: Submit an issue on GitHub
              url: https://github.com/ProjectPythia/sphinx-pythia-theme/issues/new?title=Issue%20with%20Sphinx%20Pythia%20Theme&body=Your%20issue%20content%20here.
            - name: Feedback to Project Pythia
              url: https://docs.google.com/forms/d/e/1FAIpQLSeVa1TC9xM-dk7qIE2e8bsgSrIP82yYDNw3wew3J46eREJa4w/viewform?usp=sf_link
        - title: "Join the community"
          items:
            - name: Contributor's Guide
              url: https://foundations.projectpythia.org/appendix/how-to-contribute.html
            - name: Our GitHub Organization
              url: https://github.com/ProjectPythia
    html_sidebars:
      index: []
      standalone: []
    blog_path: reference/blog
    blog_post_pattern: "reference/blog/*.md"
    blog_baseurl: "https://sphinx-pythia-theme.readthedocs.io"
    fontawesome_included: True
    post_auto_image: 1
    post_auto_excerpt: 2

  extra_extensions:
    - ablog
    - sphinx_click.ext
    - sphinx.ext.autodoc
    - sphinx.ext.intersphinx
    - sphinxcontrib.bibtex
    - sphinxcontrib.youtube
